version: '3.4'
services:
  postgres-db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanagement
    ports:
      - 5432:5432

    volumes:
      - type: bind
        source: ./database/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
